### ISSUE TITLE
No services when connecting over bluetooth?

### ISSUE THREAD

**Issue by ziriax** [thegecko/microbit-web-components#5]
When I connect a microbit:v1 over Bluetooth with a Windows 10 PC (flashed with your "universal" HEX), then

`const services = await microbit.getServices(device);`

is missing most services (e.g the button service etc is missing, but device info is there).

When I connect the microbit:v1 with an USB cable and remove the bluetooth device, I get all the services.

Is this expected behaviour?

Thanks,
Peter

**Comment by ziriax** [comment]
I compiled the bluetooth services manually from source, and now it seems to work.

**Comment by thegecko** [comment]
Strange, I just tested the universal hex on a v1 and v2 and the components on the [demo page](https://thegecko.github.io/microbit-web-components/examples/index.html) worked as expected including the button service.

**Comment by ziriax** [comment]
I think you can close this. I replaced the built-in Bluetooth on my motherboard with an USB dongle, and that works fine

However, after a random time the micro:bit V2 is freezing, no data is being send anymore, although disconnection doesn't happen immediately. 

Microsoft's PXT also suffers from this.

I reported this problem in the Codal repo, and they are investigating it.

Works fine on V1.5 devices though.
